services:
  api_gateway:
    build: ./http_api_gateway
    ports: 
      - "3000:3000"
    volumes:
      - ./http_api_gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  users_microservice:
    build: ./user_microservice
    volumes:
      - ./user_microservice/src:/usr/src/app/src
    command: npm run start:dev
  payments_microservice:
    build: ./payments_microservice
    volumes:
      - ./payments_microservice/src:/usr/src/app/src
    command: npm run start:dev
  nats:
    image: nats
    ports:
      - 4222:4222
  mysql_db:
    image: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password_123
      - MYSQL_DATABASE=nestjs_db
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testuser123
      - MYSQL_TCP_PORT=3307